title: Default Page
icon: 💜
preset: page
fields:
  text:
    label: Texte
    type: textarea
  sections:
    label: Sections
    type: structure
    fields:
      text:
        label: Texte
        type: textarea
        size: large
      style:
        label: Style
        type: text
