title: Site
preset: pages
unlisted: true

fields:
  headerHeading:
    label: Entête
    type: headline
  headerNav:
    label: Navigation
    type: pages
    text: "{{ page.menu.or(page.title) }}"
    width: 1/3
  heading:
    label: Entête
    type: textarea
    width: 1/3
  baseline:
    type: textarea
    width: 1/3

  footerHeading:
    label: Pied de page
    type: headline
  footerNav:
    label: Navigation
    type: pages
    text: "{{ page.menu.or(page.title) }}"
    width: 1/2

  globalHeading:
    label: Général
    type: headline

  ressource_type:
    label: Type de ressources
    type: structure
    width: 1/2
    fields:
      name:
        label: Type
        type: text
      icon:
        label: Icône
        type: text  
